// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

shader test(color Val_Default = color(1., 0.2, 0.7) [[ int lockgeom=0 ]],
                   output color Cout = color(0))
{
    printf("Val_Default = %f %f %f\n", Val_Default.r, Val_Default.g, Val_Default.b);
    Cout = color(Val_Default);
}
