shader
test_u_color_u_color_u_float (output color Cout = 0)
{
    color val = color(0.5*raytype("camera"), 0.75*raytype("camera"), 0.25*raytype("camera"));
    color val2 = color(0.3*raytype("camera"), 0.6*raytype("camera"), 0.8*raytype("camera"));
    
    
    float c1 = raytype("camera");
    float c2 = 0.0*raytype("camera");
              
    color col = select(val, val2, c1);    
    color col2 = col;    
    
    if (int(P[0]*64)%2==0) {    
        col2 = select(val, val2, c2);
    }

    Cout = 0.5*col + 0.5*col2;
}
