void test_strlen (string s)
{
    printf ("strlen(\"%s\") = %d\n", s, strlen(s));
}


void test_substr (string s, int begin, int len)
{
    printf ("substr(\"%s\", %d, %d) = \"%s\"\n",
            s, begin, len, substr(s,begin,len));
}


void test_substr (string s, int begin)
{
    printf ("substr(\"%s\", %d) = \"%s\"\n",
            s, begin, substr(s,begin));
}


void test_regex_match (string s, string r)
{
    printf ("regex_match (\"%s\", \"%s\") = %d\n",
            s, r, regex_match (s, r));
}



void test_regex_search (string s, string r)
{
    printf ("regex_match (\"%s\", \"%s\") = %d\n",
            s, r, regex_search (s, r));
}


void test_regex_search (string s, int results[6], string r)
{
    printf ("regex_match (\"%s\", \"%s\") = %d\n",
            s, r, regex_search (s, results, r));
    for (int i = 0;  i < arraylength(results);  ++i) {
        printf ("    results[%d] = %d\n", i, results[i]);
    }
}


void test_startswith (string s, string substr)
{
    printf ("startswith (\"%s\", \"%s\") = %d\n",
            s, substr, startswith (s, substr));
}


void test_endswith (string s, string substr)
{
    printf ("endswith (\"%s\", \"%s\") = %d\n",
            s, substr, endswith (s, substr));
}



shader
test ()
{
    printf ("test string operations:\n\n");

    // test source code string concatenation:
    printf ("Testing abutting string literals: \"%s\"\n",
            "foo" "bar" "baz");

    // Test format
    printf ("\n");
    string s = format ("P = %g", P);
    printf ("formtted string: '%s'\n", s);

    // Test concat
    printf ("\n");
    string a = "foo", b = "bar", c = "baz";
    printf ("concat(\"%s\", \"%s\", \"%s\") = \"%s\"\n",
            a, b, c, concat(a,b,c));

    // Test strlen
    printf ("\n");
    test_strlen ("");
    test_strlen ("abc");

    // Test substr
    printf ("\n");
    test_substr ("abcdefg", 0);
    test_substr ("abcdefg", 3);
    test_substr ("abcdefg", -2);
    test_substr ("abcdefg", 3, 2);
    test_substr ("abcdefg", 0, 20);
    test_substr ("abcdefg", 0, -4);

    // Test startswith/endswith
    printf ("\n");
    test_startswith ("abcdef", "abc");
    test_startswith ("abcdef", "def");
    test_startswith ("abcdef", "abcdefghi");
    test_startswith ("abcdef", "");
    test_startswith ("", "abc");
    test_startswith ("", "");
    test_endswith ("abcdef", "abc");
    test_endswith ("abcdef", "def");
    test_endswith ("abcdef", "abcdefghi");
    test_endswith ("abcdef", "ghiabcdef");
    test_endswith ("abcdef", "");
    test_endswith ("", "abc");
    test_endswith ("", "");

    // Regular expressions
    printf ("\n");
    test_regex_match ("foo", "f");         // should not match
    test_regex_match ("foo", "f[Oo]{2}");  // should match
    test_regex_match ("foo", ".*o");       // should match
    test_regex_search ("foobar.baz", "bark");     // should not match
    test_regex_search ("foobar.baz", "bar");      // should match
    test_regex_search ("foobar.baz", "[oO]{2}");  // should match

    int results[6];
    test_regex_search ("foobar.baz", results, "(f[Oo]{2}).*(.az)");
}
