struct ray {
    point pos;
    vector dir;
};

shader
test_varying_index_ray (output color Cout = color(0,0,0))
{

    // Test array referencing with varying index
    ray ray_array[3];
    ray_array[0].pos = point(.1,.2,.3);
    ray_array[0].dir = vector(.4,.5,.6); 
    ray_array[1].pos = point(.7,.8,.9);
    ray_array[1].dir = vector(1.0,1.1,1.2); 
    ray_array[2].pos = point(1.3,1.4,1.5);
    ray_array[2].dir = vector(1.6,1.7,1.8); 
    
    int varyingIndex = int(P[0]*256)%3;
    for(int i = 0; i < 5; ++i) {
        ray_array[varyingIndex].pos = point(0,0,0);
        ray_array[varyingIndex].dir = vector(0,0,0);
    }
        
    
    Cout = color(ray_array[0].pos[0]+ray_array[1].dir[2], ray_array[2].pos[1]+ray_array[0].dir[1], ray_array[0].pos[2]+ray_array[0].dir[0]);
}
