//testshade --batched --llvm_debug -g 400 400 test_sincos_w16f_w16f_w16f -od uint8 -o sinop a.tif -o cosop b.tif  -o msinop ma.tif -o cosop mb.tif | grep osl

shader test_sincos_w16f_w16f_w16f (output float sinop = 0, 
                                   output float cosop = 0,
                                   
                                   output float msinop = 0,
                                   output float mcosop = 0)
{
    

        float a = P[0];
        float b = 2.0*a;
        
        float sinop_ = 0.0;
        float cosop_ = 0.0;
            
       
        sincos(a, sinop_, cosop_);

    
    
    
    if(int(P[0]*200)%2)
{
        a = P[1];
        sincos(a, msinop, mcosop);
}
    
    sinop = sinop_;
    cosop = cosop_;
}
