//testshade --batched --llvm_debug -g 400 400 test_sincos_w16df_w16df_w16df -od uint8 -o sinop a.tif -o cosop b.tif -o dxsin s.tif -o dxcos c.tif -o dxa o.tif -o msinop ma.tif -o mcosop mb.tif -o mdxsin ms.tif -o mdxcos mc.tif -o mdxa mo.tif

shader test_sincos_w16df_w16df_w16df (output float  sinop = 0, 
				     output float cosop = 0, 
				     output float dxsin = 0,
				     output float dxcos = 0,
				     output float dxa   = 0,
				     
				     output float msinop = 0,
                     output float mcosop = 0,
                     output float mdxsin = 0,
                     output float mdxcos = 0,
                     output float mdxa = 0
                     )
                                     
{

  
        float a = P[0];
        float b = 2.0*a;
        
        float sinop_ = 0.0;
        float cosop_ = 0.0;
        
        float dxsin_ = 0.0;
        float dxcos_ = 0.0;
        float dxa_ = 0.0;
        
        sincos(a, sinop_, cosop_);
        dxsin_ = Dx(sinop_);
        dxcos_ = Dx(cosop_);
        dxa_   = Dx(a);
        
      



    if(int(P[0]*200)%2)
{
    a = P[1];
    sincos(a, msinop, mcosop);
    mdxsin = Dx(msinop);
    mdxcos = Dx(mcosop);
    mdxa   = Dx(a);

}
    
    sinop = sinop_;
    cosop = cosop_;
    dxsin = dxsin_;
    dxcos = dxcos_;
    dxa = dxa_;
    
}
