#ifndef M_PI
#define M_PI 3.14159265358979
#endif

//testshade --batched --llvm_debug -g 4 4 test_ainversesqrt2_w16f_w16f_w16f -o res a.tif | grep o

shader
inversesqrt_v_vector (output color res = 0,
               output color res_m = 0)
{
    
  vector a = vector(u, u+v, u-v);
 

 vector res_ = 0;
 res_ = inversesqrt(a); 

if (int(P[0]*200)%2){

res_m = inversesqrt(vector(v, -u-v, u+v));

}
res = res_;

}
