shader
test_normal_u_space_3xv_dfloat (string normalspace = "--param normalspace must_be_provided", output color Cout = 0)
{
    float valr = 0.5*(v);
    float valg = 0.6*(v);
    float valb = 0.4*(v);
    float val2r = u;
    float val2g = 0.3*u;
    float val2b = 0.75*u;

    normal c1 = normal(normalspace, valr, valg, valb);
    if (int(P[0]*64)%2==0) {
        c1 = normal(normalspace, val2r, val2g, val2b);
    }
    
    normal dxc = Dx(c1);
    normal dyc = Dy(c1);
    Cout = dxc + dyc;
}
