shader
test_float_2d_u_float_v_float_v_float_u_float (string type = "perlin", output color Cout = 0)
{
    float  u_val1 = raytype("camera")/4.0;
    float  u_val2 = 2.0*raytype("camera")/4.0;
    float  u_val3 = 32*raytype("camera");
    float  u_val4 = 64*raytype("camera");

    float val = pnoise (type, u_val1, u, 32*u, u_val4);
    val *= 2.0;
    Cout = val;
    if (int(P[0]*64)%2 == 0) {
        Cout[1] = pnoise (type, u_val2, v, 64*u, u_val3);
    }
}
