shader
test_float_4d_u_point_v_float_v_point_u_float (string type = "perlin", output color Cout = 0)
{
    float  u_val1 = raytype("camera")/4.0;
    float  u_val2 = 2.0*raytype("camera")/4.0;
    float  u_val3 = 32*raytype("camera");
    float  u_val4 = 64*raytype("camera");

    float val = pnoise (type, point(u_val1, u_val2, u_val1/u_val2), u, point(32*u, 64*v, 16*(u+v)), u_val3);
    val *= 2.0;
    Cout = val;
    if (int(P[0]*64)%2 == 0) {
        Cout[1] = pnoise (type, point(u_val2, u_val1, u_val2/u_val1), v, point(32*v, 64*u, 48*(u+v)), u_val4);
    }
}
