shader
test_luminance_u_color (output color Cout = 0)
{
    color c1 = color(1.0/(2*raytype("camera")), 1.0/(3*raytype("camera")), 1.0/(4*raytype("camera")));
    
    color c2 = color(2.0/(3*raytype("camera")), 2.0/(4*raytype("camera")), 2.0/(2*raytype("camera")));

    float val1 = luminance(c1);
    float val2 = 0.0;
    if (int(P[0]*64)%2==0) {
        val2 = luminance(c2);
    }
    
    Cout = color(val1, val2, val1+val2);
}
