// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

#define __OSL_XMACRO_OPNAME atan_u
#define __OSL_XMACRO_OP atan
#define __OSL_XMACRO_IN_TRANSFORM(val) (-4 + (8*val))
#define __OSL_XMACRO_OUT_TRANSFORM(val) ((M_PI_2 + val)*(1.0/M_PI))
#define __OSL_XMACRO_UNIFORM_IN

#include "../common/shaders/test_unary_xmacro.h"
