shader test_wide_op (output color Cout = 0, output color DxCout = 0)
{
   // float lambda = 1.0/(2*raytype("camera"));
    float lambda = 0.18*u;
    
    color c = 0.0;

    if(int(P[0]*200)%2)
{
    c = wavelength_color (lambda);
    
}
    Cout = c;
    DxCout = Dx(lambda);
    
}


//testshade --llvm_debug --batched -g 200 200 test_wide_op -od uint -o Cout a.tif -o DxCout b.tif | grep osl
//Calls:  call void @osl_wavelength_color_w16vw16f_masked(i8* %95, i8* %96, <16 x float> %98, i32 %100), !dbg !13


//shader
//test_luminance_u_color (output color Cout = 0)
//{
//    color c1 = color(1.0/(2*raytype("camera")), 1.0/(3*raytype("camera")), 1.0/(4*raytype("camera")));
//
//    color c2 = color(2.0/(3*raytype("camera")), 2.0/(4*raytype("camera")), 2.0/(2*raytype("camera")));
//
//    float val1 = luminance(c1);
//    float val2 = 0.0;
//    if (int(P[0]*64)%2==0) {
//        val2 = luminance(c2);
//    }
//
//    Cout = color(val1, val2, val1+val2);
//}
