shader dot_u_vector_u_vector (output float ddot = 0,
                              output float mddot = 0)
//testshade --batched --llvm_debug -g 4 4 test_dot_w16dfw16dvw16v | grep osl_dot
{

    vector a = vector(0.6, 0.2, 0.4);
    vector b = vector(0.3,0.5,0.7);
    
    float ddot_ = 0.0;
    ddot_ = dot(a,b);
    
         
    float mddot_ = 0.0;
    
              
    if(int(P[0]*200)%2){
          
       
           
           mddot_ = dot(vector(0.12, 0.22, 0.42), vector(0.56, 0.86, 0.99));
}
ddot = ddot_;
mddot = mddot_;

}
