shader dot_v_vector_v_vector (output color ddot = 0,
                                output color dxdot = 0,
                                output color dydot = 0,
                                
                                output color mddot = 0,
                                output color mdxdot = 0,
                                output color mdydot = 0)
//testshade --batched --llvm_debug -g 4 4 test_dot_w16dfw16dvw16v | grep osl_dot
{
    
    vector a = vector(u+v, -u-v, u+v);
    vector b = vector(u+v,  u+v, u+v);
    
    ddot = dot(a,b);
    dxdot = Dx(ddot);
    dydot = Dy(ddot);
    
    //float d = dot(a, b);
    
//    vector mddot_ = vector (0,0,0);
//    vector mdxdot_ = vector (0,0,0);
//    vector mdydot_ = vector (0,0,0);
    
float mddot_ = 0.0;
float mdxdot_ = 0.0;
float mdydot_ = 0.0;


if(int(P[0]*200)%2){
           a = vector(u-v, -u-v, u+v);
           mddot_ = dot(a,b+vector(0.1,0.1,0.3));
           mdxdot_ = Dx(mddot_);
           mdydot_ = Dy(mddot_);
}

mddot = mddot_;
mdxdot = mdxdot_;
mdydot = mdydot_;
}
