shader
test_transform_u_fromspace_u_tospace_u_normal (
    string fromspace = "--param fromspace must_be_provided", 
    string tospace = "--param fromspace must_be_provided", 
    output color Cout = 0)
{
    float val = 1.0/(2*raytype("camera"));
    float val2 = val/2;
    float val3 = val/4;

    normal v1 = normal(val, val2, val3);
    normal v2 = normal(val3, val, val2);
    
    normal tv = transform(fromspace, tospace, v1);
    if (int(P[0]*64)%2==0) {
        tv = transform(fromspace, tospace, v2);
    }
    Cout = tv;
}
