shader
test_transform_u_fromspace_u_tospace_v_normal (
    string fromspace = "--param fromspace must_be_provided", 
    string tospace = "--param fromspace must_be_provided", 
    output color Cout = 0)
{
    normal v1 = normal(u, v, u-v);
    normal v2 = normal(v, u, u+v);
    
    normal tv = transform(fromspace, tospace, v1);

    if (int(P[0]*64)%2==0) {
        tv = transform(fromspace, tospace, v2);
    }
    
    Cout = tv;
}
