// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/imageworks/OpenShadingLanguage

surface arrayparams (
    float farrayparam[1] = {1},
    float farrayparamunsized[] = {7,8,9},
    vector varrayparam[3] = {vector(1,2,3), vector(4,5,6), vector(7,8,9)},
    vector varrayparamunsized[] = {vector(1,1,1), vector(2,2,2), vector(3,3,3), vector(3,2,1)}
    )
{
}
