// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

#define __OSL_XMACRO_OPNAME add_v_u
#define __OSL_XMACRO_OPERATOR +
#define __OSL_XMACRO_OUT_TRANSFORM(out) 0.5*out
#define __OSL_XMACRO_UNIFORM_IN2

#include "../common/shaders/test_operator_xmacro.h"
    

    
    
    
    
