shader test_bezier_w16f_w16f_f (
	//float X = 0.5, 
	output float Fspline1 = 0
	//output float DxFspline1 = 0,
	//output float DyFspline2 = 0
)

{
   //Output: df; Input: f; Knots: df

   float fltknots[13];
   
   fltknots[ 0] =  0.0 ;
   fltknots[ 1] =  0.0 ;
   fltknots[ 2] =  1.0 ;
   fltknots[ 3] =  1.0 ;
   fltknots[ 4] =  1.0 ;
   fltknots[ 5] =  0.5 ;
   fltknots[ 6] =  0.5 ;
   fltknots[ 7] =  0.5 ;
   fltknots[ 8] =  1.0 ;
   fltknots[ 9] =  1.0 ;
   fltknots[10] =  1.0 ;
   fltknots[11] =  0.0 ;
   fltknots[12] =  0.0 ;

   float x_input[4];
   x_input[0] = 1.1;
   x_input[1] = 1.2;
   x_input[2] = 1.3;
   x_input[3] = 1.4;

  Fspline1   = spline("bezier",P[0], fltknots);
 // DxFspline1 = Dx(fltknots[9]);
 // DyFspline2 = Dy(Fspline1);



}
