shader
test_dfloat_4d_v_point_u_float_v_point_v_float (string type = "perlin", output color Cout = 0)
{
    float  u_val1 = raytype("camera")/4.0;
    float  u_val2 = 2.0*raytype("camera")/4.0;

    float val = pnoise (type, point(u, v, u - v), u_val1, point(32*u, 64*v, 16*(u+v)), 64*u);
    val *= 2.0;
    Cout = val;
    Cout[2] = Dx(val);    
    if (int(P[0]*64)%2 == 0) {
        float val2 = pnoise (type, point(v, u, v - u), u_val2, point(32*v, 64*u, 48*(u+v)), 32*v);
        Cout[1] += Dy(val2);        
    }
}
