shader
test_u_float_u_float_v_float (output color Cout = 0)
{
    float val = 1.0/(3*raytype("camera"));
    float val2 = 1.0/(4*raytype("camera"));
        
    float vc = float(int(P[1] + P[0]));
    float vc2 = float(int(1.5 - P[1]));
              
    float red = select(val, val2, vc);
    float green = select(val2, val, vc);
    float blue =  select(val, val2, vc);
    Cout = color(red,green,blue);
    
    
    if (int(P[0]*64)%2==0) {    
        green = select(2*val2, 2*val, vc2);
        blue =  select(2*val, 2*val2, vc2);
    }
        
    Cout[1] = green;
    Cout[2] = blue;
}
