shader test_spline (
	string splinename = "spline",
	output float Fspline1 = 0, 
	output float DxFspline1 = 0,

        output float mFspline1 = 0,
        output float mDxFspline1 = 0)
{

   

   float fltknots[13];
 

   fltknots[ 0] =  0.0 * (0.0/raytype("camera"));
   fltknots[ 1] =  0.0 * (0.0/raytype("camera"));
   fltknots[ 2] =  1.0 * (1.0/raytype("camera"));
   fltknots[ 3] =  1.0 * (1.0/raytype("camera"));
   fltknots[ 4] =  1.0 * (1.0/raytype("camera"));
   fltknots[ 5] =  0.5 * (0.5/raytype("camera"));
   fltknots[ 6] =  0.5 * (0.5/raytype("camera"));
   fltknots[ 7] =  0.5 * (0.5/raytype("camera"));
   fltknots[ 8] =  1.0 * (1.0/raytype("camera"));
   fltknots[ 9] =  1.0 * (1.0/raytype("camera"));
   fltknots[10] =  1.0 * (1.0/raytype("camera"));
   fltknots[11] =  0.0 * (0.0/raytype("camera"));
   fltknots[12] =  0.0 * (0.0/raytype("camera"));



  int rtype = raytype("camera");


  Fspline1 = spline(splinename, (float) rtype, fltknots);
  DxFspline1 = Dx(Fspline1);

if(P[0]>0.5)
{

  mFspline1 = spline(splinename, (float) rtype, fltknots);
  mDxFspline1 = Dx(mFspline1);


}



}
