#ifndef M_PI
#define M_PI 3.14159265358979
#endif

//testshade --batched --llvm_debug -g 4 4 test_acosh2_w16f_w16f_w16f -o res a.tif | grep o

shader
test_cosh_w16dv_w16dv (output vector res = 0,
			     output vector Dxres = 0,
			     output vector res_m = 0,
			     output vector Dxres_m = 0)
{
    
  //vector a = vector(u, u-v, u+v);
  //vector b = vector(-u, v, u-v);

vector a = u;
vector b = v;
  
  vector res_ = cosh(a); 
  vector Dxres_ = Dx(res_);

if (int(P[0]*200)%2){

res_m = cosh(b);
Dxres_m = Dx(res_m);

}

res = res_;
Dxres = Dxres_;

}
