// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

#define __OSL_XMACRO_OPNAME inversesqrt
// Do our best to make sure the results will be in [0-1] by
// transforming the input values
#define __OSL_XMACRO_VAL_TRANSFORM(val) (1.0 + (val*100.0))
#include "test_unary_xmacro.h"
    

    
    
    
    
