
//Batched:
// testshade --llvm_debug --batched -g 1024 1024 -t 1 --stats -od uint8 -o Fspline bezier_out.tif test_bezier_f_f_f | grep osl




shader test_bspline_f_f_f (output float Fspline = 0)
{

   float fltknots[13];


   fltknots[ 0] =  0.0 * u;
   fltknots[ 1] =  0.0 * u;
   fltknots[ 2] =  1.0 * u;
   fltknots[ 3] =  1.0 * u;
   fltknots[ 4] =  1.0 * u;
   fltknots[ 5] =  0.5 * u;
   fltknots[ 6] =  0.5 * u;
   fltknots[ 7] =  0.5 * u;
   fltknots[ 8] =  1.0 * u;
   fltknots[ 9] =  1.0 * u;
   fltknots[10] =  1.0 * u;
   fltknots[11] =  0.0 * u;
   fltknots[12] =  0.0 * u;


Fspline = splineinverse ("bspline", P[0], fltknots);//osl_splineinverse_w16fw16fw16f_masked

}


