shader
test (color cparam = color (.1, .7, .2),
      color cparam2 = color (.1),
      color cparam3 = color ("hsv", .1, .2, .3))
{
    printf ("  parameter initialization test: cparam = %g\n", cparam);
    printf ("  parameter initialization test2: cparam2 = %g\n", cparam2);
    printf ("\n");

    {
        float a = 0.1, b = 0.2, c = 0.5;
        printf ("  color (%g) = %g\n", a, color(a));
        printf ("  color (%g, %g, %g) = %g\n", a, b, c, color(a,b,c));
    }

    {
        printf (" varying:\n");
        float a = u;
        float b = v;
        float c = 0.5;

        printf ("  color (%g) = %g\n", a, color(a));
        printf ("  color (%g, %g, %g) = %g\n", a, b, c, color(a,b,c));
    }

    { 
        float a = 0.1, b = 0.2, c = 0.5;
        printf ("\ntesting with spaces:\n");
        printf ("  color (\"rgb\", %g, %g, %g) = %g\n",
                a, b, c, color("rgb",a,b,c));
        printf ("  color (\"hsv\", %g, %g, %g) = %g\n",
                a, b, c, color("hsv",a,b,c));
        float h, s, v, l;
        h = 0; s = 0; v = 0.5;
        printf ("  color (\"hsv\", %g, %g, %g) = %g\n",
                h, s, v, color("hsv",h,s,v));
        h = 0.5; s = 1; v = 0.5;
        printf ("  color (\"hsv\", %g, %g, %g) = %g\n",
                h, s, v, color("hsv",h,s,v));

        h = 0; s = 0; l = 0.5;
        printf ("  color (\"hsl\", %g, %g, %g) = %g\n",
                h, s, l, color("hsl",h,s,l));
        h = 0.5; s = 1; l = 0.1;
        printf ("  color (\"hsl\", %g, %g, %g) = %g\n",
                h, s, l, color("hsl",h,s,l));

        float Y = 0.5, I = 0.25, Q = 0.25;
        printf ("  color (\"YIQ\", %g, %g, %g) = %g\n",
                Y, I, Q, color("YIQ", Y,I,Q));
        float x = 0.25, y = 0.5, z = 0.25;
        printf ("  color (\"xyz\", %g, %g, %g) = %g\n",
                x, y, z, color("xyz",x,y,z));
    }

    printf ("\n");
    color c = color (0.5, 0.75, 0.75);
    printf ("  luminance(%g) = %g\n", c, luminance(c));
    c = 0.5;
    printf ("  luminance(%g) = %g\n", c, luminance(c));
}
