#if 1
float helper2(float val)
{
    float r = val;
    if (P[0] < 1.0/3.0) {        
        //return val;
        exit();
    }
    r = 0.5;
    return r;
}


float helper(float val)
{
    float r2 = helper2(val);
    //if (P[0] > 1.0/6.0) 
    {        
        r2 = 1.0;
    }
    return r2;
}
#endif

#if 1
shader test_vary7(output color c = 0.0)
{
    //float in = c;
    //float out = helper2(in);
    //float out = in;
    float r = 1.0;
    int i = 0;
    for(; i < 3; ++i)
    {
    //printf("Iteration %d\n", i);
        if (P[0] > 0.5) 
        {
            return;
            //printf("P[0](%g) > 0.5\n", P[0]);
            //if (i == 1) 
            {
                //r = 0.5;
                //exit();
                //return;
                //break;
            }
        }
    }
    //printf("Iteration %d\n", i);
    //c = r + out;    
    c = color(r, float(i)/3, 0);
}
#endif

