#if 0
float helper2(float val)
{
    float r = val;
    if (P[0] < 1.0/3.0) {        
        //return val;
        exit();
    }
    r = 0.5;
    return r;
}


float helper(float val)
{
    float r2 = helper2(val);
    //if (P[0] > 1.0/6.0) 
    {        
        r2 = 1.0;
    }
    return r2;
}
#endif

#if 0
shader test_vary6(output float c = 0.0)
{
    //float in = c;
    //float out = helper(in);
    float r = 0.0;
    //for(int i = 0; i < 3; ++i)
    {
        if (P[0] > 0.5) {
            //if (i == 2) 
            {
                r = 0.5;
                exit();
            }
        }
        #if 0
        if (i == 1) {
            r = 1.0;
        } else {
           r = 0.25;
        }
        #endif
    }
    c= r;
    //c = out;    
}
#endif

shader test_vary6(output color c = 0.0)
{
    float r = 0.0;
    float g = 0.0;
//    if (P[0] < 0.5) {
//        r = 0.25;
//    }
    if (P[0] > 0.5) {
        //r = 0.5;
        //exit();
        return;
    }   
    for(int i=0; i < 3; ++i) {
        g += 0.25;
    }
    c= color(r,g,0);
}
