#ifndef M_PI
#define M_PI 3.14159265358979
#endif

//testshade --batched --llvm_debug -g 4 4 test_pow_w16f_w16f_w16f -o res a.tif | grep o

shader
test_pow_w16v_w16v_w16v (output color res = 0,
			   output color res_m = 0)
{
    
  vector a = vector(-M_PI, -0.2, 0.1);
  vector b = vector (2.0, 1.2, 0.2);


 vector res_ = 0;
 vector res_m_ = 0;
 
 res_ = pow(u,b);

if (int(P[0]*200)%2){

res_m_ = pow(P[0],vector(0.1,0.2, 0.3));

}

res = res_;
res_m = res_m_;

}
