#ifndef M_PI
#define M_PI 3.14159265358979
#endif

//testshade --batched --llvm_debug -g 200 200 test_pow_w16dv_w16dv_w16v -od uint8 -o res a.tif -o Dxres b.tif -o res_m c.tif -o Dxres_m d.tif


shader
test_pow_w16dv_w16dv_w16v (output color res = 0,
			     output color Dxres = 0,
			     output color res_m = 0,
			     output color Dxres_m = 0)
{
    
  vector a = u;
  vector b = 2;


 res = pow(a,b); 
 Dxres = Dx(res);

if (P[0]>0.5){

res_m = pow(a,b);
Dxres_m = Dx(res_m);

}

}
