shader
test_u_int_sub_v_int (output color Cout = 0)
{
    int val = int(64*u);
    int val2 = 2*val;
                  
    int numerator = 128;
    int red = 0;
    int green = 32;
    int blue = 64;
    
    red = numerator - val;
    green = numerator - int(v);
    blue = (2*numerator) - val;
    
    if (int(P[0]*64)%2==0) {    
        red = numerator - val2;
        green = numerator - int(v);
        blue = (2*numerator) - val;
    }
    
    Cout = color(red/256.0,green/256.0,blue/256.0);
}
