// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/imageworks/OpenShadingLanguage

surface test (string filename = "",
              float s = u, float t = v,
              float swidth = 1.0, float twidth = 1.0,
              output color Cout = 0 )
{
    Cout = texture (filename, s, t, "swidth", swidth, "twidth", twidth);
}
