shader
test_mix_u_vector_v_vector_v_vector (output color Cout = 0)
{
    float  val = 1.0/(2*raytype("camera"));
    float val2 = val/2;
    float val3 = val/3;
    float val4 = val/5;
    
    vector v1 = vector(val, 0.5, val2);
    vector v2 = vector(val2, 0.5, u);
    vector v3 = vector(0, val, val2);
    vector v4 = vector(1.0, val2, v);
        
    vector v5 = vector(u, v, (u+v)/2.0);
              
    vector rv = mix(v1,v2,v5);              
        
    if (int(P[0]*64)%2==0) {
        rv = mix(v3,v4,v5);
    }
            
    Cout = rv;
}
