shader
test_dfloat_4d_u_point_u_float (string type = "perlin", output color Cout = 0)
{
    float uval = 0.133*raytype("camera");
    float uval2 = 0.777*raytype("camera");
    point up = point( 0.5*uval, 0.75*uval, 0.25*uval);    
    point up2 = point(0.33*uval2, 0.66*uval2, 0.99*uval2);
    float val = noise (type, up, uval);
    val *= 2.0;
    Cout[1] = Dy(val);    
    Cout[2] = Dx(val);    
    
    if (int(P[0]*64)%2 == 0) {
        float val2 = noise (type, up2, uval2);
        Cout[1] += Dy(val2) + Dx(val2);        
    }
}
