// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

shader
test_transform_u_tospace_v_point (
    string tospace = "--param fromspace must_be_provided", 
    output color Cout = 0)
{
    point v1 = point(u, v, u-v);
    point v2 = point(v, u, u+v);
    
    point tv = transform(tospace, v1);

    if (int(P[0]*64)%2==0) {
        tv = transform(tospace, v2);
    }
    
    Cout = tv;
}
