/////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2016 Sony Pictures Imageworks Inc., et al.
// All Rights Reserved.
// BSD 3-clause license:
// https://github.com/imageworks/OpenShadingLanguage/License.md
/////////////////////////////////////////////////////////////////////////////


shader
mx_absval
    [[ string help = "absval operator" ]]
  (
    color in = 0,
    color amount = 0,
    output color out = 0
  )
{
    out = abs(in);
}
