/////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2016 Sony Pictures Imageworks Inc., et al.
// All Rights Reserved.
// BSD 3-clause license:
// https://github.com/imageworks/OpenShadingLanguage/License.md
/////////////////////////////////////////////////////////////////////////////


shader
mx_contrast
    [[ string help = "contrast operator" ]]
  (
    color in = 0,
    color amount = 1,
    color pivot = 0.5,
    output color out = 0
  )
{
    out = (in - pivot) * amount + pivot;
}
