/////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2016 Sony Pictures Imageworks Inc., et al.
// All Rights Reserved.
// BSD 3-clause license:
// https://github.com/imageworks/OpenShadingLanguage/License.md
/////////////////////////////////////////////////////////////////////////////


shader
mx_clamp
    [[ string help = "clamp operator" ]]
  (
    color in = 0,
    color low = 0,
    color high = 1,
    output color out = 0
  )
{
    out = clamp (in, low, high);
}
