shader
test (float angle = 10, float inscale = 20,
      float offset = 0, float scale = 1,
      output color Cout = 0)
{
   // setup some coordinates
   float theta = radians(angle);
   float s = mod(u,0.25) - 0.125;
   float t = mod(v,0.5) - 0.25;
   float ru = cos(theta) * s + sin(theta) * t;
   float rv = sin(theta) * s - cos(theta) * t;
   ru *= inscale;
   rv *= inscale;
   float rz = (inscale * (s + t)) / M_SQRT2;
   float ttime = s*inscale;

   Cout = 0;
   if (v < 0.49) {
       // float noise in 1,2,3,4 dimensions
       if (u < 0.24)
           Cout = offset + scale * (float) noise(ru);
       else if (u > 0.26 && u < 0.49)
           Cout = offset + scale * (float) noise(ru, rv);
       else if (u > 0.51 && u < 0.74)
           Cout = offset + scale * (float) noise(point(ru, rv, rz));
       else if (u > 0.76)
           Cout = offset + scale * (float) noise(point(ru, rv, rz), ttime);
   } else if (v > 0.51) {
       // color noise in 1,2,3,4 dimensions
       if (u < 0.24)
           Cout = offset + scale * noise(ru);
       else if (u > 0.26 && u < 0.49)
           Cout = offset + scale * noise(ru, rv);
       else if (u > 0.51 && u < 0.74)
           Cout = offset + scale * noise(point(ru, rv, rz));
       else if (u > 0.76)
           Cout = offset + scale * noise(point(ru, rv, rz), ttime);
   }
}
