shader
test (float angle = 10, float scale = 20,
      output color Cout_f1 = 0,
      output color Cout_f2 = 0,
      output color Cout_f3 = 0,
      output color Cout_f4 = 0,
      output color Cout_c1 = 0,
      output color Cout_c2 = 0,
      output color Cout_c3 = 0,
      output color Cout_c4 = 0)
{
   // setup some coordinates
   float theta = radians(angle);
   float ru = cos(theta) * u + sin(theta) * v;
   float rv = sin(theta) * u - cos(theta) * v;
   ru *= scale;
   rv *= scale;
   float rz = cos(scale * (u + v));
   float t = sin(scale * u);

   // float noise in 1,2,3,4 dimensions
   Cout_f1 = (float) noise(ru);
   Cout_f2 = (float) noise(ru, rv);
   Cout_f3 = (float) noise(point(ru, rv, rz));
   Cout_f4 = (float) noise(point(ru, rv, rz), t);

   // color noise in 1,2,3,4 dimensions
   Cout_c1 = noise(ru);
   Cout_c2 = noise(ru, rv);
   Cout_c3 = noise(point(ru, rv, rz));
   Cout_c4 = noise(point(ru, rv, rz), t);
}
