shader
test_dvector_2d_v_float_u_float (string type = "perlin", output color Cout = 0)
{
    float uval = 0.5*(raytype("camera"));
    float uval2 = 0.75*(raytype("camera"));
    vector val = noise (type, u, uval);    
    val *= 2.0;
    Cout = Dy(val);    
    Cout -= Dx(val);    
    
    if (int(P[0]*64)%2 == 0) {
        vector val2 = noise (type, v, uval2);
        Cout += Dy(val2) + Dx(val2);
    }
}
