shader
test_dfloat_4d_v_point_u_float (string type = "perlin", output color Cout = 0)
{
    float uval = 0.133*raytype("camera");
    float uval2 = 0.777*raytype("camera");
    float val = noise (type, point(u, v, u - v), uval);
    val *= 2.0;
    Cout[1] = Dy(val);    
    Cout[2] = Dx(val);    
    
    if (int(P[0]*64)%2 == 0) {
        float val2 = noise (type, point(v, u, v - u), uval2);
        Cout[1] += Dy(val2) + Dx(val2);        
    }
}
