// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

shader
test_area_v_dpoint (output color Cout = 0)
{
    point trip1 = point(u,v,u-v);
    
    point trip2 = point(v,u,v-u);

    float val1 = area(trip1);
    float val2 = 0.0;
    if (int(P[0]*32)%2==0) {
        val2 = area(trip2);
    }
    
    Cout = color(Dx(val1), Dy(val2), Dx(val1+val2) + Dy(val1 + val2));
}
