shader trace_u_point_u_vector_u_mindist_v_maxdist(output vector cout = 0, output vector mcout = 0)
{

point src = point(0.8, 1.2, 8.0);
vector dir = vector (1.0, 0.4, 0.5);


int trace_res = 0;
int trace_res_m = trace_res;
trace_res = trace(src, dir, "mindist", 0.6, "maxdist", u, "shade", 2 );

cout = vector(trace_res+u, u, v);

if(int(P[0]*200)%2)
{
    trace_res_m = trace(src, dir, "mindist", 0.8, "maxdist", v, "shade", 3 ); 

}


mcout = vector(trace_res_m+v, tan(v/0.6), u-v);

}
