#ifndef M_PI
#define M_PI 3.14159265358979
#endif

//testshade --batched --llvm_debug -g 4 4 test_asqrt2_w16f_w16f_w16f -o res a.tif | grep o

shader
test_sqrt_w16v_w16v (output color res = 0,
			   output color res_m = 0)
{
    
  vector a = vector(u, u+v, u-v);
  vector b = 2.0*a;


 vector res_ = 0;
 res_ = sqrt(b); 

if (int(P[0]*200)%2){

res_m = sqrt(vector(v, -u-v, u+v));

}
res = res_;

}
