shader
test_v_vec_add_v_vec (output color Cout = 0)
{
    float u_float = raytype("camera");    
    float v_float = u;
    float v_float2 = v;
    
    color v_color = color(0.3*v_float,0.5*v_float, 0.75*v_float);
    color v_color2 = color(0.1*v_float2,0.2*v_float2, 0.3*v_float2);
    
    Cout = v_color + v_color2;
        
    if (int(P[0]*64)%2==0) {
        Cout = v_color + (1.5*v_color2);
    }    
}
