shader trace_v_point_v_vector_u_mindist_v_maxdist(output vector cout = 0, output vector mcout = 0)
{

    point src = point(u, v-u, u);
 vector dir = vector(0.8, 1.2, 8.0);




int trace_res = 0;
int trace_res_m = trace_res;
trace_res = trace(src, dir, "mindist", 0.6, "maxdist", u, "shade", 2 );

cout = vector(trace_res+u, u, v);

if(int(P[0]*200)%2)
{
    trace_res_m = trace(src, dir, "mindist", 0.8, "maxdist", v, "shade", 3 ); 

}


mcout = vector(trace_res_m+v, tan(v/0.6), u-v);

}
