
shader test_spline (
	string splinename="spline",
	output vector Fspline1 = 0 ,
	output vector DxFspline1 = 0,

        output vector mFspline1 = 0 ,
        output vector mDxFspline1 = 0

)

{

normal stackN = N;

int rtype = raytype("camera");

Fspline1 = spline (splinename, rtype ,stackN );
DxFspline1 = Dx(Fspline1);


 	
if(P[0]>0.5){

mFspline1 = spline (splinename, rtype ,stackN );
mDxFspline1 = Dx(mFspline1);

}

}
