shader
test_mix_v_dfloat_v_dfloat_c_float (output color Cout = 0)
{
    float  val = 1.0/(2*raytype("camera"));
    float val2 = val/2;
    float val3 = val/3;
    float val4 = val/5;
              
    float red = mix(u,v,0.5);
    float green = 0.5;
    float blue = mix(v,u, 0.7);
        
    if (int(P[0]*64)%2==0) {    
        green = mix(v,u,0.2);
        blue =  mix(u,v, 0.9);
    }
            
    Cout = color(Dx(red),green,Dy(blue));
}
