shader
test_mix_v_float_u_float_u_float (output color Cout = 0)
{
    float  val = 1.0/(2*raytype("camera"));
    float val2 = val/2;
    float val3 = val/3;
    float val4 = val/5;
              
    float red = mix(u,val2,val3);
    float green = 0.5;
    float blue = mix(u,val,val3);
        
    if (int(P[0]*64)%2==0) {    
        green = mix(v,val2,val4);
        blue =  mix(v,val3,val4);
    }
            
    Cout = color(red,green,blue);
}
