shader
test_matrix_u_fromspace_16x_v_float (
    string fromspace = "--param fromspace must_be_provided", 
    output color Cout = 0)
{
    float val = u;

    matrix m1 = matrix(fromspace, 
        0.100*val, 0.125*val, 0.150*val, 0.175*val,
        0.200*val, 0.225*val, 0.250*val, 0.275*val,
        0.300*val, 0.325*val, 0.350*val, 0.375*val,
        0.400*val, 0.425*val, 0.450*val, 0.475*val
    );

    val = v;

    matrix m2 = m1;
    if (int(P[0]*64)%2==0) {
        m2 = matrix(fromspace, 
            0.400*val, 0.425*val, 0.450*val, 0.475*val,
            0.300*val, 0.325*val, 0.350*val, 0.375*val,
            0.200*val, 0.225*val, 0.250*val, 0.275*val,
            0.100*val, 0.125*val, 0.150*val, 0.175*val
        );        
        
    }
    
    Cout = color(m2[0][0] + m2[0][1] + m2[0][2] + m2[0][3],
                 m2[1][0] + m2[1][1] + m2[1][2] + m2[1][3],
                 m2[2][0] + m2[2][1] + m2[2][2] + m2[2][3] +
                 m2[3][0] + m2[3][1] + m2[3][2] + m2[3][3]);
}
