shader test_distance_w16fw16vw16v (output float ddistance = 0,
                                   output float mddistance = 0)
//testshade --batched --llvm_debug -g 4 4 test_distance_w16dfw16dvw16v | grep osl_distance
{

    vector a = vector(1.0, 1.0, 1.0);
    vector b = P[0];
    
    
    float ddistance_ = 0.0;
    ddistance_ = distance(a,b);
              
    
    
if(int(P[0]*200)%2){
          
                
           mddistance = distance(vector(0.1,0.2,0.3),vector(0.1, 0.2, 0.3));
}

ddistance = ddistance_;
}
