// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

#include <oslutil.h>

shader
test (float K = 512, string text = "Hello World!", output color Cout = 0)
{
    float ds = u - 0.5;
    float dt = v - 0.5;
    if (ds * ds + dt * dt < 0.25)
        Cout = draw_string(text, ds * K, dt * K, 1, 1, 0);
    else
        Cout = abs(color(ds, dt, 0));
}
