shader distance_u_vector_u_vector_u_vector (output color ddistance = 0,
                                output color dxdistance = 0,
                                output color dydistance = 0,
                                
                                output color mddistance = 0,
                                output color mdxdistance = 0,
                                output color mdydistance = 0)
//testshade --batched --llvm_debug -g 4 4 test_distance_w16dfw16dvw16v | grep osl_distance
{
    
    vector a = vector(0.1, 0.1, 0.7);
    vector b = vector(0.4, 0.5, 0.6);
    vector c = vector(0.4, 0.9, -0.7);
    
    ddistance = distance(a,b,c);
    dxdistance = Dx(ddistance);
    dydistance = Dy(ddistance);
    
    //float d = distance(a, b);

    float mddistance_ = 0.0;
    float mdxdistance_ = 0.0;
    float mdydistance_ = 0.0;
    
    if(int(P[0]*200)%2){
           c = vector(0.3, 0.5, 0.6);
           mddistance_ = distance(a,b+vector(0.1,0.2,0.3), c);
           mdxdistance_ = Dx(mddistance_);
           mdydistance_ = Dy(mddistance_);
    }
    
    mddistance = mddistance_;
    mdxdistance = mdxdistance_;
    mdydistance = mdydistance_;
}
