shader test_cross_w16dvw16vw16dv (
                output color dcross = 0,
				  output color dxcross = 0,
				  output color dycross = 0,
				  
				  output color mdcross = 0,
				  output color mdxcross = 0,
				  output color mdycross = 0
				  
)
//testshade --batched --llvm_debug -g 4 4 test_dot_w16dfw16dvw16v | grep osl_dot
{
//testshade -g 200 200 test_cross_w16dvw16vw16dv -od uint8 -o dcross dcross_w16dvw16vw16dv_ref.tif -o dxcross_w16dvw16vw16dv_ref.tif -o dycross dycross_w16dvw16vw16dv_ref.tif

    
    vector a = vector(1.0, 1.0, 1.0);
    vector b = vector(u+v, -u-v, u+v);
 
    color um_dcross = cross(a,b);
    color um_dxcross = Dx(um_dcross);
    color um_dycross = Dy(um_dcross);
    
if(int(P[0]*200)%2){

          // printf ("\n");
          // printf ("cross product: d = cross(%.4g, %.4g) = %.4g  Dx(d) = %.4g  Dy(d) = %.4g\n",
          //       a, b, d, Dx(d), Dy(d));

          b = vector(-u-v, v-u, u+v);
          mdcross = cross(a,b);
          mdxcross = Dx(mdcross);
          mdycross = Dy(mdcross);
}

dcross = um_dcross;
dxcross = um_dxcross;
dycross = um_dycross;
}
