shader test_cross_w16dvw16dvw16dv (output color dcross = 0,
				  output color dxcross = 0,
				  output color dycross = 0,
				  
				  output color mdcross = 0,
				  output color mdxcross = 0,
				  output color mdycross = 0
	
				  )
//testshade --batched --llvm_debug -g 4 4 test_dot_w16dfw16dvw16v | grep osl_dot
{
   vector a = vector(u+v, u-v, u+v);
   vector b = vector(u+v,  u+v, u+v);
   
//   dcross = cross(a,b);
//   dxcross = Dx(dcross);
//   dycross = Dy(dcross);

   color um_dcross = cross(a,b);
   color um_dxcross = Dx(um_dcross);
   color um_dycross = Dy(um_dcross);
   
   vector _dcross = 0;
   vector _dxcross = 0;
   vector _dycross = 0;
   
  
   
if(int(P[0]*200)%2){
 
	   _dcross = cross(vector(u,v,u),vector(u-v, u+v, v-u));
	   _dxcross = Dx(_dcross);
	   _dycross = Dy(_dcross);
}
    dcross = um_dcross;  
    dxcross = um_dxcross;  
    dycross = um_dycross;  

 mdcross = _dcross;  
 mdxcross = _dxcross;  
 mdycross = _dycross;  



}
