// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage


#include "runsplineinverse.h"

shader test_splineinverse_u_float_u_floatarray (
    output float Fout = 0)
{
    float uniform_x = 0.5*raytype("camera");
    float uniform_scale = 0.75*raytype("camera");

    Fout = run_all_fsplineinverses(uniform_x, uniform_scale);

}
