#include "mystruct.h"

void status (float variable, string name)
{
    printf ("%s connected: %d  (value=%g)\n",
            name, isconnected(variable), variable);
}


void status (MyStruct variable, string name)
{
    printf ("%s connected: %d  (value=%g)\n",
            name, isconnected(variable), variable);
    status (variable.x, concat(name, ".x"));
}


shader test (float a = 0, float b = 0,
             float c = 0 [[ int lockgeom=0 ]],
             MyStruct mystruct1 = {0,0},
             MyStruct mystruct2 = {0,0})
{
    printf ("a=%g\n", a);   // force retrieval/execution of upstream layer
    printf ("Downstream:\n");
    status (a, "a");
    status (b, "b");
    status (c, "c");
    status (mystruct1, "mystruct1");
    status (mystruct2, "mystruct2");
}
