// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/imageworks/OpenShadingLanguage

shader a
(
    float frequency = 1,
    string noiseType = "perlin",
    color amplitude = 1,
    int seed = 0,
    output color out = 0
)
{
    point domain = point(u + seed, v + seed, 0) * frequency;
    out = noise(noiseType, domain[0], domain[1]) * amplitude;
}
