shader test ()
{
    printf ("Testing break: (should never let i get beyond 3)\n");
    for (int i = 0;  i < 10; ++i) {
        if (i > 3)
            break;
        printf ("  i = %d\n", i);
    }


    printf ("\nTesting continue:\n");
    for (int i = 0;  i < 10;  ++i) {
        printf ("  i = %d\n", i);
        if (i > 3)
            continue;
        printf ("  should only print this if i <= 3.\n");
    }
}

