shader
pow_v_dv_base_v_df_exp (output color res = 0,
                 output color Dxres = 0,
                 output color res_m = 0,
                 output color Dxres_m = 0)
{
    
  vector a = u;
  float b = P[1];
  vector c = u-v;


 vector res_ = 0;
 vector Dxres_ = 0;
 
 res_ = pow(a,b); 
 Dxres_ = Dx(res_);

if (int(P[0]*200)%2){

res_m = pow(c,b);
Dxres_m = Dx(res_m);

}

res = res_;
Dxres = Dxres_;

}
