#ifndef M_PI
#define M_PI 3.14159265358979
#endif

//testshade --batched --llvm_debug -g 4 4 test_atan2_w16f_w16f_w16f -o res a.tif | grep o

shader
atan2_v_vector_v_vector (output color res = 0,
               output color res_m = 0)
{
    
  vector a = vector(v, u, v-u);
  vector b = vector(u, v, u-v);


 vector res_ = 0;
 res_ = atan2(a,b); 

if (int(P[0]*200)%2){
a =  vector(u, -v, u+v);
res_m = atan2(a,b);

}
res = res_;

}
