shader
test_u_float_v_float_u_int (output color Cout = 0)
{
    float val = 1.0/(2*raytype("camera"));
    float val2 = 1.0/(4*raytype("camera"));
    
    
    int c1 = raytype("camera");
    int c2 = 0*raytype("camera");
              
    float red = select(val, P[0], c1);
    float green = select(val2, P[1], c1);
    float blue =  select(val, P[2], c2);
    Cout = color(red,green,blue);
    
    
    if (int(P[0]*64)%2==0) {    
        green = select(val2, P[1], c2);
        blue =  select(val, P[2], c1);
    }
        
    Cout[1] = green;
    Cout[2] = blue;
}
