shader
test_u_float_v_float_v_int (output color Cout = 0)
{
    float val = 1.0/(2*raytype("camera"));
    float val2 = 1.0/(4*raytype("camera"));
    
    
    int vc = (P[1] > P[0]);
    int vc2 = int(P[0] + P[1]);
              
    float red = select(val, P[0], vc);
    float green = select(val2, P[1], vc);
    float blue =  select(val, P[2], vc);
    Cout = color(red,green,blue);
    
    
    if (int(P[0]*64)%2==0) {    
        green = select(val2, P[1], vc2);
        blue =  select(val, P[2], vc2);
    }
        
    Cout[1] = green;
    Cout[2] = blue;
}
