shader
test_vector_4d_v_point_u_float_v_point_u_float (string type = "perlin", output color Cout = 0)
{
    float  u_val1 = raytype("camera")/4.0;
    float  u_val2 = 2.0*raytype("camera")/4.0;
    float  u_val3 = 32*raytype("camera");
    float  u_val4 = 64*raytype("camera");

    vector val = pnoise (type, point(u, v, u - v), u_val1, point(32*u, 64*v, 16*(u+v)), u_val3);
    val *= 2.0;
    Cout = val;
    if (int(P[0]*64)%2 == 0) {
        vector val2 = pnoise (type, point(v, u, v - u), u_val2, point(32*v, 64*u, 48*(u+v)), u_val4);
        val2 *= 1.125;
        Cout = val2;
    }
}
