shader
test_vector_2d_u_float_v_float_u_float_v_float (string type = "perlin", output color Cout = 0)
{
    float  u_val1 = raytype("camera")/4.0;
    float  u_val2 = 2.0*raytype("camera")/4.0;
    float  u_val3 = 32*raytype("camera");
    float  u_val4 = 64*raytype("camera");

    vector val = pnoise (type, u_val1, u, u_val3, 32*u);
    val *= 2.0;
    Cout = val;
    if (int(P[0]*64)%2 == 0) {
        vector val2 = pnoise (type, u_val2, v, u_val4, 64*v);
        val2 *= 1.125;
        Cout = val2;
    }
}
