// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

#define __OSL_XMACRO_OPNAME logb_u
#define __OSL_XMACRO_OP logb
#define __OSL_XMACRO_IN_TRANSFORM(val) (100*(val)*(val))
#define __OSL_XMACRO_OUT_TRANSFORM(val) val/6
#define __OSL_XMACRO_UNIFORM_IN

#include "../common/shaders/test_unary_xmacro.h"
