shader test_spline (
	string splinename="spline", 
	output vector Fspline1 = 0, 
	//output vector DxFspline1 = 0,

        output vector mFspline1 = 0
   //     output vector mDxFspline1 = 0

	
	)
{

  vector vecknots[13];

   vecknots[ 0] =  0.0;
   vecknots[ 1] =  0.0;
   vecknots[ 2] =  1.0;
   vecknots[ 3] =  1.0;
   vecknots[ 4] =  1.0;
   vecknots[ 5] =  0.5;
   vecknots[ 6] =  0.5;
   vecknots[ 7] =  0.5;
   vecknots[ 8] =  1.0;
   vecknots[ 9] =  1.0;
   vecknots[10] =  1.0;
   vecknots[11] =  0.0;
   vecknots[12] =  0.0;

   float mvalue = 2.0*(1.0/raytype("camera"));

  Fspline1   = spline(splinename, mvalue, vecknots);
 // DxFspline1 = Dx(P[1]);

if(P[0]>0.5){

  mFspline1   = spline(splinename, mvalue, vecknots);
  //mDxFspline1 = Dx(P[1]);
}
}
