// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage



shader
test ()
{
    string shadername = "unknown";
    string layername  = "unknown";
    string groupname  = "unknown";
    getattribute ("shader:shadername", shadername);
    getattribute ("shader:layername", layername);
    getattribute ("shader:groupname", groupname);

    printf ("shader name: %s\n", shadername);
    printf ("layer name:  %s\n", layername);
    printf ("group name:  %s\n", groupname);
}
