shader test_spline ( 
	string splinename="spline",
	output float Fspline1 = 0,
	output float mFspline1 = 0
)

{

   float fltknots[13];
   
   fltknots[ 0] =  0.0 ;
   fltknots[ 1] =  0.0 ;
   fltknots[ 2] =  1.0 ;
   fltknots[ 3] =  1.0 ;
   fltknots[ 4] =  1.0 ;
   fltknots[ 5] =  0.5 ;
   fltknots[ 6] =  0.5 ;
   fltknots[ 7] =  0.5 ;
   fltknots[ 8] =  1.0 ;
   fltknots[ 9] =  1.0 ;
   fltknots[10] =  1.0 ;
   fltknots[11] =  0.0 ;
   fltknots[12] =  0.0 ;

Fspline1   = spline(splinename,P[0], fltknots);

if(P[0]>0.5){
 mFspline1   = spline(splinename,P[0], fltknots);
}


}
