shader
test_v_float_div_v_float (output color Cout = 0)
{
    // Quantize divisor to avoid disagreements between scalar & SIMD as it approaches 0
    float divisor = float(64-int(64*u))/64;
     
              
    float numerator = u;
    float red = 0.0;
    float green = 0.5;
    float blue = 1.0;
    red = numerator/divisor;
    green = numerator/int(v);
    blue = v/divisor;
    
    Cout = color(red,green,blue);
}
