#include "runspline.h"

shader test_deriv_spline_u_float_u_colorarray (
    output color ValOut = 0,
    output color DxOut = 0,
    output color DyOut = 0)
{
    float uniform_x = 0.5*raytype("camera");
    color uniform_scale = color(0.5, 0.75, 1.0)*raytype("camera");

    color value = run_all_csplines(uniform_x, uniform_scale);
    color dxVal = Dx(value);
    color dyVal = Dy(value);
    ValOut = value;
    DxOut = dxVal;
    DyOut = dyVal;
}