// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage


#include "runspline.h"

shader test_deriv_spline_c_float_c_colorarray (
    output color ValOut = 0,
    output color DxOut = 0,
    output color DyOut = 0)
{
    color value = run_all_csplines(0.5, color(0.5, 0.75, 1.0));
    color dxVal = Dx(value);
    color dyVal = Dy(value);
    ValOut = value;
    DxOut = dxVal;
    DyOut = dyVal;
}
