// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

#define __OSL_XMACRO_SUFFIX u_u_v_v
#define __OSL_XMACRO_IN_TRANSFORM(...) (10*(__VA_ARGS__))
#define __OSL_XMACRO_STRIPE_TRANSFORM(...) (10-(__VA_ARGS__))
#define __OSL_XMACRO_UNIFORM_IN

#define __OSL_XMACRO_IN_TRANSFORM2(...) (20*(__VA_ARGS__))
#define __OSL_XMACRO_STRIPE_TRANSFORM2(...) (20-(__VA_ARGS__))
#define __OSL_XMACRO_UNIFORM_IN2

#include "../common/shaders/test_pnoise4d_xmacro.h"
