// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

#define __OSL_XMACRO_SUFFIX u_v
#define __OSL_XMACRO_IN_TRANSFORM(...) (10*(__VA_ARGS__))
#define __OSL_XMACRO_STRIPE_TRANSFORM(...) (10-(__VA_ARGS__))
#define __OSL_XMACRO_UNIFORM_IN

#include "../common/shaders/test_pnoise3d_xmacro.h"
