
//Batched:
// testshade --llvm_debug --batched -g 1024 1024 -t 1 --stats -od uint8 -o Fspline bezier_out.tif test_bezier_f_f_f | grep osl




shader test_constant_f_f_f (output float Fspline = 0)
{

   float fltknots[13];


   fltknots[ 0] =  0.0;
   fltknots[ 1] =  0.0;
   fltknots[ 2] =  1.0;
   fltknots[ 3] =  1.0;
   fltknots[ 4] =  1.0;
   fltknots[ 5] =  0.5;
   fltknots[ 6] =  0.5;
   fltknots[ 7] =  0.5;
   fltknots[ 8] =  1.0;
   fltknots[ 9] =  1.0;
   fltknots[10] =  1.0;
   fltknots[11] =  0.0;
   fltknots[12] =  0.0;


Fspline = splineinverse ("constant", P[0], fltknots);//osl_splineinverse_w16fw16ff_masked



}


