#ifndef M_PI
#define M_PI 3.14159265358979
#endif



shader
test_fmod_w16dv_w16dv_w16dv (output color res = 0,
			     output color Dxres = 0,
			     output color res_m = 0,
			     output color Dxres_m = 0)
{
    
  vector a = u;
  vector b = v;

  vector res_ = 0;
  vector Dxres_ = 0;
  
  res_ = fmod(a,b);
  Dxres_ = Dx(res);

  if (int(P[0]*200)%2){
    res_m = fmod(b,a);
    Dxres_m = Dx(res_m);

  }
  
  res = res_;
  Dxres = Dxres_;

}
