#ifndef M_PI
#define M_PI 3.14159265358979
#endif

//testshade --batched --llvm_debug -g 4 4 test_fmod_w16df_w16f_w16df -o res a.tif -o Dxres b.tif -o res_m c.tif -o Dxres_m d.tif | grep osl

shader
test_fmod_w16df_w16f_w16df (output color res = 0,
			      output color Dxres = 0,
			      output color Dxb = 0,
			      output color res_m = 0,
			      output color Dxres_m = 0,
			      output color Dxb_m = 0)
{
    
        float a = M_PI;
        float b = P[0];

        float res_ = 0.0;
        float Dxres_ = 0.0;
        float Dxb_ = 0.0;
        
    res_ = fmod(a,b);
	Dxres_ = Dx(res_);
	Dxb_ = Dx(b);

if (P[0]>0.5){

res_m = fmod(b,a);
Dxres_m = Dx(res_m);
Dxb_m = Dx(b);

}

res = res_;
Dxres = Dxres_;
Dxb = Dxb_;

}
