#ifndef M_PI
#define M_PI 3.14159265358979
#endif

//testshade --batched --llvm_debug -g 200 200 test_fmod_w16df_w16df_w16f -od uint8 -o res a.tif -o Dxres b.tif -o res_m c.tif -o Dxres_m d.tif

shader
test_fmod_w16df_w16df_w16f (output color res = 0,
			      output color Dxres = 0,
			      output color res_m = 0,
			      output color Dxres_m = 0)
{
    
        float a = u;
        float b = M_PI;
        
        float res_ = 0.0;
        float Dxres_ = 0.0;
        
        res_ = fmod(a,b);
	    Dxres_ = Dx(res_);

if (int(P[0]*200)%2){

res_m = fmod(b,a); //fmod(b,b) fails
Dxres_m = Dx(res_m);

}

res = res_;
Dxres = Dxres_;

}
