shader
test_transform_v_tospace_v_dpoint (output color Cout = 0)
{
    point v1 = point(u, v, u-v);
    point v2 = point(v, u, u+v);
    
    string tospaces[5] = { "common", "object", "shader", "world", "camera"};
    string tospace = tospaces[int(P[0]*64)%5];
    
    
    point tv = transform(tospace, v1);

    if (int(P[0]*64)%2==0) {
        tv = transform(tospace, v2);
    }
    
    Cout = Dx(tv) + Dy(tv);
}
