shader
test_transform_u_tospace_u_point (
    string tospace = "--param fromspace must_be_provided", 
    output color Cout = 0)
{
    float val = 1.0/(2*raytype("camera"));
    float val2 = val/2;
    float val3 = val/4;

    point v1 = point(val, val2, val3);
    point v2 = point(val3, val, val2);
    
    point tv = transform(tospace, v1);

    if (int(P[0]*64)%2==0) {
        tv = transform(tospace, v2);
    }
    
    Cout = tv;
}
