shader
test_dvector_2d_u_float_v_float_v_float_v_float (string type = "perlin", output color Cout = 0)
{
    float  u_val1 = raytype("camera")/4.0;
    float  u_val2 = 2.0*raytype("camera")/4.0;

    vector val = pnoise (type, u_val1, u, 32*u, 32*v);
    val *= 2.0;
    Cout = val;
    Cout = Dx(val);    
    if (int(P[0]*64)%2 == 0) {
        vector val2 = pnoise (type, u_val2, v, 64*u, 64*v);
        Cout += Dy(val2);        
    }
}
