shader
test_dvector_1d_u_float_u_float (string type = "perlin", output color Cout = 0)
{
    float  u_val1 = raytype("camera")/4.0;
    float  u_val2 = 32*raytype("camera");
    float  u_val3 = 64*raytype("camera");

    vector val = pnoise (type, u_val1, u_val2);
    val *= 2.0;
    Cout = val;
    Cout = Dx(val);    
    if (int(P[0]*64)%2 == 0) {
        vector val2 = pnoise (type, u_val2, u_val2);
        Cout += Dy(val2);        
    }
}
